from exer_8_5_rotate import rotate_word

def make_word_dict():
    """Read the words in words.txt and return a dictionary
    that contains the words as keys
    """
    d = dict()
    for line in open('words.txt'):
        word = line.strip().lower()
        d[word] = None
    return d


def rotate_pairs(word, word_dict):
    """Prints all words that can be generated by rotating word.

    word: string
    word_dict: dictionary with words as keys
    """
    for i in range(1, 14):
        rot = rotate_word(word, i)
        if rot in word_dict:
            print("{} rotating {} is {}".format(word, i, rot))


if __name__ == "__main__":
    wdict = make_word_dict()
    for word in wdict:
        rotate_pairs(word, wdict)
